version: '3.8'

services:
  tillywork:
    image: tillywork/tillywork:latest
    ports:
      - '80:80'
      - '3000:3000'
    env_file:
      - .env
    command: '/start.sh'
    depends_on:
      - db
      - redis
    volumes:
      - tillywork:/app/uploads

  db:
    image: postgres:16.3-bullseye
    volumes:
      - tillywork:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${TW_DB_NAME}
      POSTGRES_USER: ${TW_DB_USERNAME}
      POSTGRES_PASSWORD: ${TW_DB_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:7.2.5-alpine
    restart: unless-stopped

volumes:
  tillywork:
